### ISSUE TITLE
fastForward on RecurrenceSet

### ISSUE THREAD

**Issue by pli2019** [dmfs/lib-recur#123]
Hi,

I am using RecurrenceSet and it does not support fastForward().

RecurrenceSet recurSet = new RecurrenceSet(firstInstance, new RuleInstances(rule), excetpitonList);

Is there an alternate way to use fastForward on a recurrence event with exceptions?  I found org.dmfs.rfc5545.recurrenceset.RecurrenceSetIterator but it is deprecated.

Thanks.

**Comment by dmfs** [comment]
the way this is supposed to work now is by decorating the `InstanceIterable` like this

```java
RecurrenceSet recurSet = new RecurrenceSet(
    firstInstance,
    new FastForwarded(fastForwardTo, new RuleInstances(rule)),
    excetpitonList);
```

**Comment by pli2019** [comment]
Thanks for the reply.  It works!
