### ISSUE TITLE
Question: filtering RecurrenceSet within a given interval

### ISSUE THREAD

**Issue by janusvm** [dmfs/lib-recur#124]
Given a RecurrenceSet comprising both RRULE RuleInstances and an RDATE InstanceList, is there a built-in way to limit the iterator to only yield instances within a given interval, i.e. after some start date and before some end date?

I tried at first with a combination of RecurrenceRule.setUntil and FastForwarded, but this would still include RDATEs after the end date, as they're not part of the rule itself.

**Comment by janusvm** [comment]
I realize now that this is not actually necessary for my use-case (wrapped calls in a Clojure program), as the sequence generated from the RecurrenceSet can be filtered after the fact just fine and act as expected with e.g.

```clojure
(->> (create-recurrence-set recur-data)  ; recur-data defines a potentially infinite RRULE + some DTSTART
  (take-while #(date-after? end-date %))  ; stops iterating at first instance that's not on or before end-date
```

and I guess similarly in Java with e.g. `Stream#takeWhile` (or comparing dates in a for/while loop).

**Comment by dmfs** [comment]
@janusvm this is exactly what I would have suggested too. In Java you could use streams to achieve that as you described, but for my taste this is a bit too cumbersome. I'll add something that is simpler.

**Comment by janusvm** [comment]
Perhaps it could be described akin to how FastForwarded, taking two dates instead of one, but it otherwise used in the same context (e.g. something a là `Bounded(DateTime, DateTime, InstanceIterable)`).

**Comment by dmfs** [comment]
Something like that might work, although in this case we could make it a decorator of the `RecurrenceSet` like this:

```java
new Before(untildate, new RecurrenceSet(....));
```
and
```java
new AtOrBefore(untildate, new RecurrenceSet(....));
```
I guess that would be a bit inconsistent with `FastForwared` though.
