### ISSUE TITLE
RecurrenceRule.setByDayPart doesn't remove BYDAY part when given an empty list

### ISSUE THREAD

**Issue by janusvm** [dmfs/lib-recur#127]
Calling `RecurrenceRule#setByDayPart` with an empty list seems to include that empty list in the parts map — I believe it's due to a missing `else` or `return` in the method:

https://github.com/dmfs/lib-recur/blob/d59e8668c0e4ffa9b1bc207e16f9a41984ef302d/src/main/java/org/dmfs/rfc5545/recur/RecurrenceRule.java#L1957-L1965

This makes the resulting rule have an empty BYDAY-value, e.g. `"FREQ=MONTHLY;BYMONTHDAY=31;BYDAY="`, eventually leading to an "too many empty recurrence sets" exception when expanding the rule.

**Comment by dmfs** [comment]
Admittedly, the setters never were a real use case for me so far, that's probably why they are so poorly tested. Thanks for reporting and fixing this. I hope there are no other bad surprises there.
