### ISSUE TITLE
additional event if DTSTART hour is different from RRULE byhour

### ISSUE THREAD

**Issue by mossbauer** [dmfs/lib-recur#22]
``` java

RecurrenceRule r11 = new RecurrenceRule("FREQ=WEEKLY;BYHOUR=10;COUNT=10", RecurrenceRule.RfcMode.RFC5545_LAX);
DateTime start = new DateTime(TimeZone.getTimeZone("America/Chicago"),2016, 1, 1,9,0,0);

RecurrenceRuleIterator rri = r11.iterator(start);
while(rri.hasNext()) {
        System.out.println(rri.nextDateTime());
}
```

Produces:

**20160201T090000**
20160201T100000
20160208T100000
20160215T100000
20160222T100000
20160229T100000
20160307T100000
20160314T100000
20160321T100000
20160328T100000

**Comment by dmfs** [comment]
That's actually by intention. [RFC 5545](https://tools.ietf.org/html/rfc5545#section-3.8.5.3) states:

> The "DTSTART" property defines
>      the first instance in the recurrence set. 

So we've made sure that the first instance iterated is always the start instance.

It also states:

> The recurrence set generated with a "DTSTART" property
>      value not synchronized with the recurrence rule is undefined.

So I think it's ok to handle it like this and I think that's how most other implementations handle it.

We're currently planning a large number of changes for the 1.0 release. One of them could be to make the iteration of an unsynchronized start optional.

**Comment by dmfs** [comment]
@mossbauer it's probably too late for you, but I've finally come to the conclusion that it's indeed better to let the recurrence iterator just iterate all actual instances of the rule and inject the start instance at a later stage.
