### ISSUE TITLE
Help: Can't understand exception thrown

### ISSUE THREAD

**Issue by carotorrehdz** [dmfs/lib-recur#23]
Hi! I found your library and it's just exactly what I need, but for some reason I can seem to create a correct RecurrenceRule.

This is what I'm writing:

``` java
RecurrenceRule rule = new RecurrenceRule(Freq.WEEKLY);

try {
    rule.setByPart(Part.INTERVAL, 1);
    Log.d(TAG, rule.toString());
} catch (InvalidRecurrenceRuleException e) {
   e.printStackTrace();
}
```

But this exception is thrown every time and I can't print a correct rule:

![screen shot 2016-07-11 at 2 19 36 pm](https://cloud.githubusercontent.com/assets/3819186/16743538/8a7d162c-4772-11e6-8bcd-079591c0008a.png)

I'm using `lib-recur-0.9.3.jar` and following some sample code from this repo readme, I'll be grateful if you can point to a correct direction. Thanks!

**Comment by dmfs** [comment]
You can't set an interval using the `setByPart` method. This method is only for parts that start with `BY`, i.e. `BYMONTH`, `BYDAY` …
To set an interval use `setInterval(int)`. Of course you don't have to set that for `1` since that's the default anyway.

**Comment by carotorrehdz** [comment]
I don't know how I overlooked that method! Thanks for your help and congrats on such a cool library!
