### ISSUE TITLE
Seconds value in occurrences is not set according to DTSTART

### ISSUE THREAD

**Issue by timopulkkinen** [dmfs/lib-recur#27]
Hi,

with this rule (BYSECOND missing): WKST=MO;FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SU;INTERVAL=1;BYHOUR=21;BYMINUTE=0;DTSTART=20161022T210000Z

the iterated occurrences have timestamps with invalid seconds value, for example 20161024T210048, should be 20161024T210000?

br,
Timo

**Comment by dmfs** [comment]
Sounds like the start value you're passing to `iterate(DateTime)` has non-zero seconds. See my response to #26, the `DTSTART` part is not valid and hence ignored. What matters is the seconds of the start that you pass.

**Comment by timopulkkinen** [comment]
Ok, thanks! I'll test this right away.
