### ISSUE TITLE
RecurrenceSet always returns start date as the first DateTime if that date (event) doesn't occur in rrule

### ISSUE THREAD

**Issue by bonjourrohit89** [dmfs/lib-recur#35]
Hi, I have the following rule
String rrule="FREQ=DAILY;BYDAY=SA,SU;UNTIL=20171130T000000Z" and my start date is "20171101T000000Z"

Here start date is 1 November 2017 and end date is 30 November 2017 now the event will be occur only on saturday and sunday as per rrule mean (4,5,11,12,18,19,25,26Nov) but Problem is that event is also occuring for 1 November where day is Wednesday which should not be happen. Please tell me why I am getting 1 November event. Below is my code ,please check and provide the best solution for this

       DateTime firstInstance = DateTime.parse("20171101T000000Z");
       RecurrenceRule rRuleForSession = null;
                        try {
                            rRuleForSession = new RecurrenceRule(rrule);
                        } catch (InvalidRecurrenceRuleException e) {
                            e.printStackTrace();
                        }
        RecurrenceSet rset = new RecurrenceSet();
        rset.addInstances(new RecurrenceRuleAdapter(rRuleForSession));
       rset.addExceptions(new RecurrenceList("20171130T000000Z", firstInstance.getTimeZone()));

       RecurrenceSetIterator itrRecurrence = 
       rset.iterator(firstInstance.getTimeZone(),firstInstance.getTimestamp());
                        
                 int maxInstance = 1;
                        while (itrRecurrence.hasNext() && --maxInstance >= 0) {
                            long nextInstance = itrRecurrence.next();
                            DateTime dateTime = new DateTime(TimeZone.getDefault(), nextInstance);
                            Toast.makeText(baseActivity,dateTime.toString(),Toast.LENGTH_SHORT).show();
                             }

**Comment by dmfs** [comment]
This is intended behavior. `RecurrenceSet` adds another instance for the start date, see https://github.com/dmfs/lib-recur/blob/master/src/main/java/org/dmfs/rfc5545/recurrenceset/RecurrenceSet.java#L116

[RFC 5545, page 54](https://tools.ietf.org/html/rfc5545#page-54) explicitly states:
>The "DTSTART" property for a "VEVENT" specifies the inclusive
>start of the event.  For recurring events, it also specifies the
>**very first instance in the recurrence set**.

(emphasis by me)

If you want to start iterating at a specific time which is after the actual start date, you could consider using the [`fastForard(long)`](https://github.com/dmfs/lib-recur/blob/master/src/main/java/org/dmfs/rfc5545/recurrenceset/RecurrenceSetIterator.java#L223) method of `RecurrenceSetIterator`

**Comment by bonjourrohit89** [comment]
hello, 
Thanks for the  response,
But I still have a small doubt, Can you please explain a bit how to exclude first date using fastforward method

**Comment by dmfs** [comment]
I guess at present your only option would be to copy the sources of `RecurrenceSet` and remove [Line 117](https://github.com/dmfs/lib-recur/blob/master/src/main/java/org/dmfs/rfc5545/recurrenceset/RecurrenceSet.java#L117) in your copy.

The library is based on RFC 5545 which explicitly states that this behavior is preferable. Yet I see the need for this and I'll consider something to omit the start if it's not part of the rule.

**Comment by dmfs** [comment]
I have rewritten the recurrence set iterator code. Now you can chose to iterate or omit the first instance if it's not synchronized with the rule. Hope this works for everyone.
Please check out README.md for guidance and let me know if you have any questions.
