### ISSUE TITLE
RecurrenceRuleIterator returns date with 1 hour difference with relation to TimeZone.

### ISSUE THREAD

**Issue by rhlmshr** [dmfs/lib-recur#59]
Recurrence rule code that I am using is: 
`
RecurrenceRule rule = null;

        TimeZone timeZone = TimeZone.getTimeZone("Asia/Dhaka");

        print(timeZone.toString());

        SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMdd'T'HHmmss", Locale.US);

        String start = "20190603T000000";

        String end = "20190616T000000";

        DateTime startDateTime = new DateTime(DateUtils.getTimeInMilliseconds(start, formatter));

        DateTime endDateTime = new DateTime(DateUtils.getTimeInMilliseconds(end, formatter));

        try {
            rule = new RecurrenceRule("FREQ=WEEKLY;INTERVAL=1;WKST=MO;BYDAY=TU");
        } catch (InvalidRecurrenceRuleException e) {
            print(e.toString());
        }

        rule.setUntil(endDateTime);

        RecurrenceRuleIterator it = rule.iterator(startDateTime);

        int maxInstances = 100; // limit instances for rules that recur forever

        while (it.hasNext() && (!rule.isInfinite() || maxInstances-- > 0)) {
            DateTime nextInstance = it.nextDateTime();
            print(maxInstances + " -- " + nextInstance.toString());
        }
`

Expected results: 

1 | Mon, | 03 | Jun | 2019 | 23:30:00 |
2 | Mon, | 10 | Jun | 2019 | 23:30:00 |

Result I am getting:

20190604T003000Z
20190611T003000Z

There is a hour difference between the results. Can you please help me in this regard?

**Comment by dmfs** [comment]
What's your local time zone? I suspect the milliseconds you get from DateUtils are somehow off.

In which time zone are the start and end times supposed to be in?

Have you tried this?
```
DateTime startDateTime = DateTime.parse(timeZone, start);
DateTime endDateTime = DateTime.parse(timeZone, end);
```
It's better to provide the time zone explicitly when parsing a local date/time value.

**Comment by rhlmshr** [comment]
Thanks for the response. I tried using the method you gave above. 

`
    public static List<String> getDatesFromRRule(String rrule) {
        List<String> dateList = new ArrayList<>();

        rrule = "DTSTART;TZID=Asia/Calcutta:20190811T000000\nRRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=SU,SA;UNTIL=20191012T000000";

        String timezone = rrule.substring(rrule.indexOf("=") + 1, rrule.indexOf(":"));
        String dtStart = rrule.substring(rrule.indexOf(":") + 1, rrule.indexOf("\n"));
        String rule = rrule.substring(rrule.indexOf("RRULE:") + 6);

//        this
//        DateTime start = DateTime.parse(TimeZone.getTimeZone(timezone), dtStart);
        DateTime start = DateTime.parse(dtStart);

        try {
            RecurrenceRule recurrenceRule = new RecurrenceRule(rule);

//         And this here....
            RecurrenceRuleIterator iterator = recurrenceRule.iterator(start.getTimestamp(), TimeZone.getTimeZone(timezone));

            while (iterator.hasNext()) {
                Log.w("abbc", String.format("%s\n", iterator.nextDateTime().toString()));
            }
        } catch (InvalidRecurrenceRuleException e) {
            e.printStackTrace();
        }

        return dateList;
    }`

And this is giving me this error: java.lang.IllegalArgumentException: using floating start times with absolute until values (and vice versa) is not allowed.

I am unable to assign timezone to the rrule this way.

**Comment by dmfs** [comment]
When your start time is absolute (i.e. bound to a specific time zone) the until date must be absolute too, i.e. it must be a UTC time stamp. So convert `20191012T000000` from your time zone to UTC and append a `Z`.

**Comment by dmfs** [comment]
To be more specific, RFC 5545 doesn't allow the TZID parameter on RRULE, hence the until date must use UTC when being used with an absolute start time.

**Comment by rhlmshr** [comment]
After going through several iterations, I have created this Utils class to get list of dates from given rrule.

`public class RRuleUtils {

    public static final String TAG = RRuleUtils.class.getSimpleName();

    public static List<String> getDatesFromRRule(String rrule) {

        List<String> dateList = new ArrayList<>();

        String timezone = rrule.substring(rrule.indexOf("=") + 1, rrule.indexOf(":"));
        String dtStart = rrule.substring(rrule.indexOf(":") + 1, rrule.indexOf("\n"));
        String rule = rrule.substring(rrule.indexOf("RRULE:") + 6, rrule.lastIndexOf(";"));
        String dtUntil = rrule.substring(rrule.lastIndexOf("=") + 1);

        SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMdd'T'HHmmss", Locale.US);
        formatter.setTimeZone(TimeZone.getTimeZone(timezone));

        DateTime start = DateTime.parse(timezone, dtStart);
        DateTime until = new DateTime(DateUtils.getTimeInMilliseconds(dtUntil, formatter));

        try {
            RecurrenceRule recurrenceRule = new RecurrenceRule(rule);
            recurrenceRule.setUntil(until);

            RecurrenceRuleIterator iterator = recurrenceRule.iterator(start);

            while (iterator.hasNext()) {
                DateTime currDateTime = iterator.nextDateTime();
                Log.w(TAG, String.format("%s\n", currDateTime.toString()));
                dateList.add(DateUtils.convertDateToString(
                        new Date(currDateTime.getTimestamp()),
                        new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US)));
            }

        } catch (InvalidRecurrenceRuleException e) {
            e.printStackTrace();
        }

        return dateList;
    }
}`

Thanks for the prompt response and all the help that you have provided.

**Comment by dmfs** [comment]
Just to reiterate, using an absolute start time (i.e. a time with a time zone) and an `UNTIL` clause which is **not** in `UTC` (i.e. doesn't end with `Z`), is not valid as per RFC 5545.

Anyway, if that doesn't matter to you, you can simplify your method to 
```Java
  public static List<String> getDatesFromRRule(String rrule)
    {
        List<String> dateList = new ArrayList<>();

        String timezone = rrule.substring(rrule.indexOf("=") + 1, rrule.indexOf(":"));
        String dtStart = rrule.substring(rrule.indexOf(":") + 1, rrule.indexOf("\n"));
        String rule = rrule.substring(rrule.indexOf("RRULE:") + 6);

        DateTime start = DateTime.parse(dtStart);

        try
        {
            RecurrenceRule recurrenceRule = new RecurrenceRule(rule);
            RecurrenceRuleIterator iterator = recurrenceRule.iterator(start);

            while (iterator.hasNext())
            {
                DateTime currDateTime = iterator.nextDateTime().swapTimeZone(TimeZone.getTimeZone(timezone));
                dateList.add(
                        DateUtils.convertDateToString(
                        new Date(currDateTime.getTimestamp()),
                        new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US)));
            }

        }
        catch (InvalidRecurrenceRuleException e)
        {
            e.printStackTrace();
        }

        return dateList;
    }
```
The method now ignores the time zone when doing the recurrence expansion and applies it afterwards to the results.
