### ISSUE TITLE
Adding exception rule followed by exception date string results in undesired behaviour

### ISSUE THREAD

**Issue by deepakbulani** [dmfs/lib-recur#64]
Say my RRule is **FREQ=DAILY;DTSTART=20190927T000000Z;BYHOUR=13;BYMINUTE=27** 
When i try to add following exception rule by recurrenceset.addException(new RecurrenceRuleAdapter()) -**FREQ=DAILY;BYHOUR=13;BYMINUTE=27;UNTIL=20190930T000000Z** followed by exdates by recurrenceset.addException(new RecurrenceList()):  **20191001T132700Z,20191002T132700Z**
RecurrenceSetIterator yields next instance to be 2019-09-28T13:27Z[UTC] which is undesired.

**Comment by deepakbulani** [comment]
removing either exception rule or exdates as exceptions results in correct behaviour.
1.Removing exception rule as an exception results in first instance to be 2019-09-27T13:27Z[UTC] and 5th instance as 2019-10-03T13:27Z[UTC] which is correct.
2.Removing exdates as an exception results in first instance to be 2019-09-30T13:27Z[UTC]  which is correct.

**Comment by dmfs** [comment]
Which version do you use? I've fixed a similar issue recently.

**Comment by dmfs** [comment]
See https://github.com/dmfs/lib-recur/releases/tag/0.11.2

**Comment by deepakbulani** [comment]
Thanks,it resolved my problem.I was using 0.10.1 for my application. Upgraded to 0.11.2. 
Closing the issue.

**Comment by dmfs** [comment]
better go straight to https://github.com/dmfs/lib-recur/releases/tag/0.11.3

**Comment by deepakbulani** [comment]
I also had one other requirement.
For my use case i am using **RecurrenceSet** to support  **recurrenceRule,exceptionRule** as well **exdates** and i also want my unsynchronized start date(say in future) to be skipped.
for past start dates i am using fast forward to current date but for future start dates if i fast forward (say by 1 second) then for rules in which start dates are synchronized with the rule their first instance is skipped.
Is there a way to achieve my use case?
i know RecurrenceRuleIterator now skips startdate if not synchronized with rule but i have to use RecurrenceSetIterator to iterate.Any help would be appreciated.
Thanks.

**Comment by dmfs** [comment]
@deepakbulani please open a new issue for this. It's not related to the original request and it needs some discussion on how to handle this case.

**Comment by deepakbulani** [comment]
Yes sure, hence closing this.
