### ISSUE TITLE
Update org.dmfs.rfc5545.recur.RecurrenceRule to support REST APIs

### ISSUE THREAD

**Issue by jay-mancini** [dmfs/lib-recur#89]
Goal is the send RecurrenceRule over REST API. One of two things need to change:

1. org.dmfs.rfc5545.recur.RecurrenceRule Add empty constructor public RecurrenceRule() 
2. Remove final from the RecurrenceRule class so that a developer can extend it and be able to add an empty constructor.

Thanks and great work on this library.

**Comment by jay-mancini** [comment]
Created pull request for changes to support REST API as JSON/XML.
https://github.com/dmfs/lib-recur/pull/90

**Comment by dmfs** [comment]
Can you give an example of how you intend to use this? I see a problem with the changes in #90. In particular it allows creating an invalid/incomplete `RecurrenceRule` object. Until now, an instance of `RecurrenceRule` is always guaranteed to represent a valid recurrence rule. With this change in place that's no longer true. Maybe we can find a better solution to this.

**Comment by jay-mancini** [comment]
We want to be able to serialize and deserialize the RecurrenceRule to send to from and REST API calls

**Comment by jay-mancini** [comment]
The work around for now is to use the rrule.toString and send the string over REST API instead of the object.

**Comment by dmfs** [comment]
That's actually way better. I wouldn't call it a workaround. To me this sounds like the correct solution.
