### ISSUE TITLE
Some recurrence exceptions are ignored

### ISSUE THREAD

**Issue by jmerljak** [dmfs/lib-recur#93]
Let's configure RecurrenceSetIterator:

- RRule: `FREQ=WEEKLY;UNTIL=20200511T000000Z;BYDAY=TU`
- start: `1586880000000` (2020-04-14T16:00Z)
- exception instances: `[1587484800000, 1588694400000]` (2020-04-21T16:00Z and 2020-05-05T16:00Z)

It should produce the following:
`[1586880000000, 1588089600000]` (2020-04-14T16:00Z and 2020-04-28T16:00Z)

However, it returns `1588694400000` (2020-05-05T16:00Z) as well.

Version: 0.12.1

**Comment by dmfs** [comment]
Thanks for reporting. I see the problem and will provide a fix asap.

**Comment by dmfs** [comment]
Fixed in 0.12.2.

**Comment by jmerljak** [comment]
Thanks for the quick response. Much appreciated!
