### ISSUE TITLE
Possible documentation errors

### ISSUE THREAD

**Issue by markdiamond** [dmfs/lib-recur#99]
First, thanks for building this great library. 
I'm only a novice Java programmer, so I might be wrong, but ...
Your README.md seems to have some errors.  The statement:
RecurrenceRule rule1 = new RecurrenceRule("FREQ=WEEKLY;BYWEEKNO=1,2,3,4;BYDAY=SU", RfcMode.RFC2445_STRICT);
	// -> will iterate Sunday in the first four weeks of the year
seems to be wrong. Is the same true of example 2?

Also, under Building Rules, it looks like Parts.BYMONTH should be Part.BYMONTH ... in several examples.

**Comment by dmfs** [comment]
> Also, under Building Rules, it looks like Parts.BYMONTH should be Part.BYMONTH ... in several examples.

right, I'll fix these

> RecurrenceRule rule1 = new RecurrenceRule("FREQ=WEEKLY;BYWEEKNO=1,2,3,4;BYDAY=SU", RfcMode.RFC2445_STRICT);
// -> will iterate Sunday in the first four weeks of the year
seems to be wrong. Is the same true of example 2?

true, RFC 2445 says about `BYWEEKNO`:

> This rule part is only valid for YEARLY rules.

I'll check whether just the documentation is incorrect or whether the implementation is wrong too.
